/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package quotes;
import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {


    public static void main(String[] args) throws IOException {
        try {
            String url = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            InputStreamReader inputStreamReader = new InputStreamReader(connection.getInputStream());
            BufferedReader bufferedReader = new BufferedReader(inputStreamReader);
            String data = bufferedReader.readLine();
            Gson gson = new Gson();
            Api api = gson.fromJson(data, Api.class);
            System.out.println("the count is >>> " + api);
            System.out.println("the previous is >>> " + api.getAuthor());
            System.out.println("the results is >>> " + api.getText());
        } catch (Exception e) {
            String fileName = "/home/bader/quotes/app/src/main/java/resources/recentquotes.json";

            Gson gson = new Gson();
    
                FileReader fileReader = new FileReader(fileName);
                JsonReader reader = new JsonReader(fileReader);
                Quotes[] data = gson.fromJson(reader, Quotes[].class);
                Random random = new Random();
                int pos = random.nextInt(data.length);
                System.out.println(data[pos]);}

    }
    }
